compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://nexus.medcontrol.cloud/repository/all_npm"

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - x64
  os:
    - current
    - linux

# yarnPath: .yarn/releases/yarn-4.0.1.cjs
