version: "3"


dotenv:
  - .env

tasks:
  venv:
    desc: "Create venv"
    cmds:
      - source services/server/.venv/bin/activate

  infra:up:
    desc: "Start infrastructure"
    cmds:
      - docker compose -f docker-compose.infra.yaml up -d

  infra:down:
    desc: "Start infrastructure"
    cmds:
      - docker compose -f docker-compose.infra.yaml down

  start:miniapp:
    desc: "Run miniapp"
    dir: "services/miniapp"
    cmds:
      - npm run dev

  start:main:
    desc: "Run main"
    dir: "apps/server"
    cmds:
      - yarn dev

  start:worker:
    desc: "Run worker"
    dir: "apps/server"
    cmds:
        - yarn worker
