version: "3"


dotenv:
  - .env

tasks:
  venv:
    desc: "Create venv"
    cmds:
      - source services/server/.venv/bin/activate

  infra:up:
    desc: "Start infrastructure"
    cmds:
      - docker compose -f docker-compose.infra.yaml up -d

  infra:down:
    desc: "Start infrastructure"
    cmds:
      - docker compose -f docker-compose.infra.yaml down

  start:miniapp:
    desc: "Run miniapp"
    dir: "services/miniapp"
    cmds:
      - npm run dev

  start:main:
    desc: "Run main"
    dir: "services/server"
    cmds:
      - poetry run main

  start:worker-1:
    desc: "Run worker 1"
    dir: "services/server"
    cmds:
      - poetry run worker worker_1

  start:worker-2:
    desc: "Run worker 2"
    dir: "services/server"
    cmds:
      - poetry run worker worker_2

  start:flower:
    desc: "Run celery UI"
    dir: "services/server"
    cmds:
      - celery -A src.app.adapters.celery_runner.singleton:celery_app flower
